### ISSUE TITLE
reload of ich wipes out templates

### ISSUE THREAD

**Issue by dtipson** [HenrikJoreteg/ICanHaz.js#43] opened 2012-01-23 18:31 UTC
Pretty easy to work around, but when including ICH with yepnope, it seems possible for the library to reinitialize in some edges cases, and in doing so, all the previously imported templates will be wiped out (since they are tagged as already having been processed, so the new copy of ich overwrites the old one and then finds no new templates to import from the DOM).  I've just been adding window.ich = window.ich || ich= {  all the ich code...; } as a workaround (basically, if the library is already included, don't bother to overwrite it with a new copy), but not sure that's the best/right solution.  The right solution is not to include it twice, obviously, but it's not always possible to avoid in some situations. :)

**Comment by HenrikJoreteg** [comment] 2012-01-23 19:26
I'm not quite sure what I can do to help here. ICanHaz only inits itself once when it's included.

**Comment by dtipson** [comment] 2012-01-24 21:25
But it wipes out all it's templates if it's included a second time.  This can be prevented if the final assignment is window.ich = window.ich || ich;

**Comment by HenrikJoreteg** [comment] 2012-01-24 21:29
I would argue that woud be unexpected behavior. If you "overwrite" ich by initting it twice it _should_ wipe 'em out because you're replacing ICH with another instance altogether. 

This seems like a problem in the code that is using ICH not in ICH itself. Wouldn't you agree?

**Comment by HenrikJoreteg** [comment] 2012-02-27 05:48
Because as you described this is an edge case. I don't want to make this change in the main library. I'd look into why it's initializing twice, perhaps file a bug in yep/nope if appropriate. I'm gonna close this for now. Thanks

**Closed as completed by HenrikJoreteg** 2012-02-27 05:48 UTC
